version: '3.8'

services:
  db:
    image: mysql:8.3.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_LOWER_CASE_TABLE_NAMES: 0
    ports:
      - "3306:3306"
    volumes:
      - ./packages/data/mysql:/var/lib/mysql