name: 部署前端

on:
    push:
        branches:
            - main
        paths:
            - 'packages/frontend/admin-art/**'

jobs:
    buildDeployment:
        runs-on: ubuntu-latest
        environment: Development
        steps:
            - name: 迁出代码
              uses: actions/checkout@main

            - name: 安装Node环境
              uses: actions/setup-node@main
              with:
                  node-version: lts/*

            - name: 设置缓存
              uses: actions/cache@v3
              with:
                  path: ~/.local/share/pnpm/store
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: 安装pnpm
              uses: pnpm/action-setup@v4

            - name: 安装依赖
              run: pnpm install

            - name: 打包项目
              run: pnpm run build:frontend-admin-art

            - name: 上传到服务器
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: root
                  key: ${{ secrets.SERVER_PRIVATE_KEY }}
                  port: 22
                  source: 'packages/frontend/admin-art/dist/**'
                  target: '/www/wwwroot/logistics_management/frontend'
