name: Build Deployment

on:
    workflow_dispatch: # 添加手动触发事件
    # push:
    #     branches:
    #         - main
    #     paths:
    #         - 'packages/**'

jobs:
    buildDeploymentFrontend:
        runs-on: ubuntu-latest
        environment: Development
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install NodeJS Environment
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Cache PNPM Store
              uses: actions/cache@v4
              with:
                  path: ~/.local/share/pnpm/store
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install PNPM
              uses: pnpm/action-setup@v4

            - name: Install Dependencies
              run: pnpm install

            - name: Build Frontend Project
              run: pnpm run build:frontend-admin-art

            - name: Upload To Server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: root
                  key: ${{ secrets.SERVER_PRIVATE_KEY }}
                  port: 22
                  source: 'packages/frontend/admin-art/dist'
                  target: '/www/wwwroot/logistics_management/frontend/'
                  strip_components: 4

    buildDeploymentBackend:
        runs-on: ubuntu-latest
        environment: Development
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Update To Server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: root
                  key: ${{ secrets.SERVER_PRIVATE_KEY }}
                  port: 22
                  source: 'packages/backend'
                  target: '/www/wwwroot/logistics_management/backend/'
                  strip_components: 2

            # - name: 安装依赖并启动服务
            #   run: |
            #       ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} << 'EOF'
            #       cd /www/wwwroot/logistics_management/backend
            #       pnpm install --prod --filter backend
            #       pm2 restart backend || pm2 start dist/index.js --name backend
            #       EOF
