name: 部署后端

on:
    push:
        branches:
            - main
        paths:
            - '/packages/backend/**'

jobs:
    buildDeployment:
        runs-on: ubuntu-latest
        environment: Development
        steps:
            - name: 迁出代码
              uses: actions/checkout@main

            - name: 上传到服务器
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: root
                  key: ${{ secrets.SERVER_PRIVATE_KEY }}
                  port: 22
                  source: '/packages/backend/**'
                  target: '/www/wwwroot/logistics_management/backend'
