name: Build Deploy Frontend

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'frontend/admin-art/**'

jobs:
    PublishDockerImage:
        name: Publish Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Pull Existing Image For Cache
              run: |
                  docker pull ${{ secrets.DOCKER_USERNAME }}/logistics-management-frontend:latest || true

            - name: Build Docker Image
              run: |
                  docker build --platform linux/amd64 \
                  --cache-from=${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:latest \
                  -t ${{ secrets.DOCKER_USERNAME }}/logistics-management-frontend:latest \
                  -f ./frontend/admin-art/Dockerfile ./frontend/admin-art

            - name: Push Docker Image
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/logistics-management-frontend:latest

            - name: Deploy Frontend To Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{secrets.SERVER_USERNAME}}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      docker pull ${{ secrets.DOCKER_USERNAME }}/logistics-management-frontend:latest
                      docker stop logistics-management-frontend || true
                      docker rm logistics-management-frontend || true
                      docker run -dp ${{ secrets.SERVER_SITE_PORT }}:80 \
                      -p 80:80 \
                      --name logistics-management-frontend  \
                      ${{ secrets.DOCKER_USERNAME }}/logistics-management-frontend:latest

    # DeployBackend:
    #     name: Deploy Frontend
    #     runs-on: ubuntu-latest
    #     needs: PublishDockerImage
    #     steps:
    #         - name: Deploy Frontend To Server
    #           uses: appleboy/ssh-action@master
    #           with:
    #               host: ${{ secrets.SERVER_HOST }}
    #               port: ${{ secrets.SERVER_PORT }}
    #               username: ${{secrets.SERVER_USERNAME}}
    #               key: ${{ secrets.SSH_PRIVATE_KEY }}
    #               script: |
    #                   docker pull ${{ secrets.DOCKER_USERNAME }}/logistics-management-frontend:latest
    #                   docker stop logistics-management-frontend || true
    #                   docker rm logistics-management-frontend || true
    #                   docker run -dp ${{ secrets.SERVER_SITE_PORT }}:80 \
    #                   --name logistics-management-frontend  \
    #                   ${{ secrets.DOCKER_USERNAME }}/logistics-management-frontend:latest
