name: Build Deploy Backend

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'backend/**'
env:
    IMAGE_NAME: logistics-management-backend
    IMAGE_TAG: latest
    IMAGE_FULL_TAG: ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

jobs:
    PublishDockerImage:
        name: Publish Docker Image
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "环境变量：${{ env.IMAGE_NAME }} ${{ env.IMAGE_TAG }} ${{ env.IMAGE_FULL_TAG }}"
                    echo "环境变量：$IMAGE_FULL_TAG"

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Pull existing image for cache
              run: |
                  docker pull ${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:latest || true

            - name: Build Docker Image
              run: |
                  IMAGE_TAG=$(date +%Y%m%d%H%M%S)
                  docker build --platform linux/amd64 \
                  --cache-from=${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:latest \
                  -t ${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:latest \
                  -f ./backend/Dockerfile ./backend
                  echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

            - name: Push Docker Image
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:latest

            - name: Deploy Backend To Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{secrets.SERVER_USERNAME}}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      docker pull ${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:latest
                      docker stop logistics-management-backend || true
                      docker rm logistics-management-backend || true
                      docker run -dp ${{ secrets.SERVER_BACKEND_HOST }}:9094 \
                      --name logistics-management-backend \
                      ${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:latest

    # DeployBackend:
    #     name: Deploy Backend
    #     runs-on: ubuntu-latest
    #     needs: PublishDockerImage
    #     steps:
    #         - name: Deploy Backend To Server
    #           uses: appleboy/ssh-action@master
    #           with:
    #               host: ${{ secrets.SERVER_HOST }}
    #               port: ${{ secrets.SERVER_PORT }}
    #               username: ${{secrets.SERVER_USERNAME}}
    #               key: ${{ secrets.SSH_PRIVATE_KEY }}
    #               script: |
    #                   docker pull ${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:${{ env.IMAGE_TAG }}
    #                   docker stop logistics-management-backend || true
    #                   docker rm logistics-management-backend || true
    #                   docker run -dp ${{ secrets.SERVER_BACKEND_HOST }}:3000 \
    #                   --name logistics-management-backend \
    #                   ${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:${{ env.IMAGE_TAG }}
