name: Build Deploy Backend

on:
    workflow_dispatch:
    push:
        branches:
            - main
        # paths:
        #     - 'backend/**'

jobs:
    PublishDockerImage:
        name: Publish Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build Docker Image
              run: |
                  IMAGE_TAG=$(date +%Y%m%d%H%M%S)
                  docker build --platform linux/amd64 \
                  -t ${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:$IMAGE_TAG \
                  -f ./backend/Dockerfile ./backend
                  echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

            - name: Push Docker Image
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:$IMAGE_TAG

    DeployBackend:
        name: Deploy Backend
        runs-on: ubuntu-latest
        needs: PublishDockerImage
        steps:
            - name: Deploy Backend To Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{secrets.SERVER_USERNAME}}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      docker pull ${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:$IMAGE_TAG
                      docker stop logistics-management-backend || true
                      docker rm logistics-management-backend || true
                      docker run -dp ${{ secrets.SERVER_BACKEND_HOST }}:3000 \
                      --name logistics-management-backend \
                      ${{ secrets.DOCKER_USERNAME }}/logistics-management-backend:$IMAGE_TAG
