name: Docker Build Deployment

on:
    workflow_dispatch: # 添加手动触发事件
    push:
        branches:
            - main
        paths:
            - 'packages/**'

jobs:
    BuildDeploymentFrontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            # 设置 Docker 环境
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            # 构建 Docker 镜像
            - name: Build Docker Image
              run: |
                  docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/logistics-management:latest .

            # 推送 Docker 镜像到 DockerHub
            - name: Push Docker Image
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/logistics-management:latest

            # 上传前端文件到服务器
            - name: Update To Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{secrets.SERVER_USERNAME}}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      docker pull ${{ secrets.DOCKER_USERNAME }}/logistics-management:latest
                      docker stop logistics-management || true
                      docker rm logistics-management || true
                      docker run -d --name logistics-management -p ${{ secrets.SERVER_SITE_PORT }}:80 ${{ secrets.DOCKER_USERNAME }}/logistics-management:latest
