name: 更新到服务器

on:
    push:
        # push 代码的时候 哪个分支会受到影响 这里是 v1.0.0 分支
        branches:
            # - v1.0.0 # 也可以设置为 main 分支
            - main

# 推送之后执行一系列的任务
jobs:
    build:
        runs-on: debian-11
        steps:
            # 获取代码
            - name: 迁出代码
              # 使用action库 action/checkout获取代码
              uses: actions/checkout@main
            # 安装Node环境

            - name: 安装node.js
              # 使用action库  actions/setup-node安装node
              uses: actions/setup-node@main
              with:
                  node-version: lts/*

            - name: 安装pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: latest

            # 安装依赖
            - name: 安装依赖
              run: pnpm install

            # 打包
            - name: 打包
              run: pnpm run build:frontend-admin-art

    deploy:
        permissions:
            contents: none
        runs-on: debian-11
        needs: build
        steps:
            # 获取代码
            - name: 迁出代码
              uses: actions/checkout@main

            # 上传到服务器
            - name: 上传到服务器
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: root
                  key: ${{ secrets.SERVER_PRIVATE_KEY }}
                  port: 22
                  source: 'packages/frontend/admin-art/dist/'
                  target: '/www/wwwroot/frontend'
