name: 更新到服务器

on:
    push:
        # push 代码的时候 哪个分支会受到影响 这里是 v1.0.0 分支
        branches:
            # - v1.0.0 # 也可以设置为 main 分支
            - main

jobs:
    buildDeployment:
        runs-on: ubuntu-latest
        steps:
            - name: 迁出代码
              uses: actions/checkout@main

            - name: 安装node.js
              uses: actions/setup-node@main
              with:
                  node-version: lts/*

            - name: 安装pnpm
              uses: pnpm/action-setup@v4

            - name: 安装依赖
              run: pnpm install

            - name: 打包
              run: pnpm run build:frontend-admin-art

            - name: 上传到服务器
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: root
                  key: ${{ secrets.SERVER_PRIVATE_KEY }}
                  port: 22
                  source: 'packages/frontend/admin-art/dist/'
                  target: '/www/wwwroot/frontend'
